name: bank_sha
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.9
  intl: ^0.18.0
  another_flushbar: ^1.12.29
  http: ^0.13.5
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  image_picker: ^0.8.6+2
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/